theme: jekyll-theme-hacker
title: Hi! I'm Renato
description: I'm a Computer Science student. I am always learning something.
author: 
    name: Renato Rodríguez Llanos
    email: renatorodriguezllanos@gmail.com
    url: renatoseb.github.io
owner: Renato Rodríguez Llanos
year: 2021
